### ISSUE TITLE
add configuration to enable/disable zoom

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [EarthJournalismNetwork/jeo-plugin#55] opened 2020-03-23 18:20 UTC

**Comment by leopiccionia** [comment] 2020-03-23 20:48
Is it a duplicate of #46?

**Comment by bwstefano** [comment] 2020-05-04 23:03
This setting should be labeled as:
"Disable zoom on post" -> "Disable scroll zoom on post"

Also zoom buttons should always appear on maps, like the map at https://dialogochino.net/31057-chinas-brazilian-beef-demand-linked-to-amazon-deforestation-risk/

**Comment by bwstefano** [comment] 2020-05-15 22:12
If I mouse over the zoom buttons, the plus and minus signs disappear, when only their backgrounds should be turned gray. See below:

![IMG_20200515_190822_trim](https://user-images.githubusercontent.com/11841075/82100390-e4e04d80-96df-11ea-8d31-eadd12d9dba4.jpg)

**Closed** 2020-05-15 22:15 UTC
